### PR TITLE
chinese translation revision Z. Zhou & Z

### PR DESCRIPTION
**Pull request by arjunhassard**
Most recent translation by Zhen and 'Z' – includes source code, assets and pdf. 

There isn't an obvious way to organize the different translations in one repo – @michwill mentioned that using branches is not ideal (of course, that's not what branches are for). So I suggest keeping the english assets at the root directory as they are, and just storing each translation as an individual folder containing all the assets in that same directory. For the chinese translation, that folder is called 'wp chinese source' - happy to rename.

### CODE REVIEW

**Comment by mswilkison** [comment]
Do we have some way to indicate which version of the English source the translations are current with?

**Comment by mswilkison** [comment]
For example, the current English whitepaper lists David's NuCypher affiliation while this translation appears to be based on an older version which lists him as NICS.

**Comment by arjunhassard** [comment]
@mswilkison Good point. Spoke to Zhen, he's chasing up mystery hombre 'Z' (who began this translation revision process), to find out which version he initially worked off. If it's a pre-March version, we'll need to go through the commits since then together and get it up to date

**Comment by arjunhassard** [comment]
Update @mswilkison - spoke to translator team and we've worked out which updates took place on the English version since the latest Chinese translation. They'll work on it this weekend

**Comment by mswilkison** [comment]
This is a close, yeah?

**Pull request closed without merging**
